lagoon_id: "kirah"
source: rockwell
poll_seconds: 1

timezone: "America/Mexico_City" 


backend:
  url: "http://127.0.0.1:8090/ingest/scada"

rockwell:
  ip: "192.168.22.10"
  slot: 0

tags:
  PT115_R: "PT115_R"
  PT119_R: "PT119_R"
  PT122_R: "PT122_R"
  PT123_R: "PT123_R"
  PT143_R: "PT143_R"
  FIT002_R: "FIT002_R"
  WM01_TOT: "WM01_TOT"
  BACKWASH.DIFF_PRES : "BACKWASH_DIFF_PRES"
  P002_ST: "P002_ST"
  P006_ST: "P006_ST"
  P007_ST: "P007_ST"
  RETRO_SCADA: "RETRO_SCADA"
  P017_ST: "P017_ST"
  P016_ST: "P016_ST"
  P015_ST: "P015_ST"
  VE288_ST: "VE288_ST"
  VE318_ST: "VE318_ST"
  VE322_ST: "VE322_ST"
  VE320_ST: "VE320_ST"
  FILTRACION.ST: "FILTRACION.ST"
  P001_ST: "P001_ST"
  LF_ST: "LF_ST"
  PT100_R: "PT100_R"
  PT103_R: "PT103_R"
  FIT001_R: "FIT001_R"
  TE110_R: "TE110_R"
  TH110_R: "TH110_R"

