lagoon_id: "laguna_aquaterra"
product_type: "crystal"
source: rockwell
poll_seconds: 1
timezone: "America/Asuncion"

backend:
  url: "http://127.0.0.1:8090/ingest/scada"
  timeout_sec: 5

rockwell:
  ip: "192.168.12.10"
  timeout_sec: 5

tags:
  PT117_R_SCADA: "PT117_R_SCADA"
  PT120_R_SCADA: "PT120_R_SCADA"
  PT121_R_SCADA: "PT121_R_SCADA"
  PT122_R_SCADA: "PT122_R_SCADA"
  WM01_TOT: "WM01_TOT"
  BACKWASH.DIFF_PRES: "BACKWASH.DIFF_PRES"
  P002_STS_SCADA: "P002_STS_SCADA"
  P006_STS_SCADA: "P006_STS_SCADA"
  P007_STS_SCADA: "P007_STS_SCADA"
  VE318_STS_SCADA: "VE318_STS_SCADA"
  VE320_STS_SCADA: "VE320_STS_SCADA"
  VE322_STS_SCADA: "VE322_STS_SCADA"
  VE288_STS_SCADA: "VE288_STS_SCADA"
  P017_STS_SCADA: "P017_STS_SCADA"
  P015_STS_SCADA: "P015_STS_SCADA"
  P016_STS_SCADA: "P016_STS_SCADA"

event_tags:
  P002_STS_SCADA: "ESTADO BOMBA RETROLAVADO"
  P006_STS_SCADA: "ESTADO BOMBA FILTRACION"
  P007_STS_SCADA: "ESTADO BOMBA RETORNO CLARIFICADO"
  VE318_STS_SCADA: "ESTADO VALVULA VE-318"
  VE320_STS_SCADA: "ESTADO VALVULA VE-320"
  VE322_STS_SCADA: "ESTADO VALVULA VE-322"
  VE288_STS_SCADA: "ESTADO VALVULA VE-288"
  P017_STS_SCADA: "ESTADO BOMBA CL-FLO12"
  P015_STS_SCADA: "ESTADO BOMBA A-C1LO"
  P016_STS_SCADA: "ESTADO BOMBA F-H1LO"
