lagoon_id: "laguna_mountain_view"
product_type: "crystal"
source: rockwell
poll_seconds: 1

force_reconnect_every_sec: 3600
max_consecutive_fails: 10

timezone: "Africa/Cairo"

backend:
  url: "http://127.0.0.1:8090/ingest/scada"

rockwell:
  ip: "192.168.26.10"
  slot: 0
  timeout_sec: 5

tags:
  PT203_R: "PT203_R"
  PT303_R: "PT303_R"
  PT401_R: "PT401_R"
  FIT400_R: "FIT400_R"
  FIT420_R: "FIT420_R"
  PT402_R: "PT402_R"
  PT404_R: "PT404_R"
  PT406_R: "PT406_R"
  WM01_TOT: "WM01_TOT"
  BACKWASH.DIFF_PRES: "BACKWASH.DIFF_PRES"
  P300_ST: "P300_ST"
  P200_ST: "P200_ST"
  P500_ST: "P500_ST"
  MP110_ST: "MP110_ST"
  MP401_ST: "MP401_ST"
  MP400_ST: "MP400_ST"
  VE400_ST: "VE400_ST"
  VE402_ST: "VE402_ST"
  VE414_ST: "VE414_ST"
  VE416_ST: "VE416_ST"
  FILTRACION.ST: "FILTRACION.ST"
  PT213_R: "PT213_R"
  PT313_R: "PT313_R"
  PT420_R: "PT420_R"
  PT422_R: "PT422_R"
  PT424_R: "PT424_R"
  PT426_R: "PT426_R"
  BACKWASH_2.DIFF_PRES: "BACKWASH_2.DIFF_PRES"
  P310_ST: "P310_ST"
  P210_ST: "P210_ST"
  MP421_ST: "MP421_ST"
  MP420_ST: "MP420_ST"
  VE420_ST: "VE420_ST"
  VE422_ST: "VE422_ST"
  VE434_ST: "VE434_ST"
  VE436_ST: "VE436_ST"
  FILTRACION_2.ST: "FILTRACION_2.ST"
  P100_ST: "P100_ST"
  LF01_ST: "LF01_ST"
  PT101_R: "PT101_R"
  PT102_R: "PT102_R"
  FIT100_R: "FIT100_R"
  TE100_R: "TE100_R"
  TH101_R: "TH101_R"
  P100_FREQ: "P100_FREQ"
  P110_ST: "P110_ST"
  LF02_ST: "LF02_ST"
  PT111_R: "PT111_R"
  PT112_R: "PT112_R"
  FIT110_R: "FIT110_R"
  TE110_R: "TE110_R"
  TH111_R: "TH111_R"
  P110_FREQ: "P110_FREQ"
  P120_ST: "P120_ST"
  LF03_ST: "LF03_ST"
  PT121_R: "PT121_R"
  PT122_R: "PT122_R"
  FIT120_R: "FIT120_R"
  TE120_R: "TE120_R"
  TH121_R: "TH121_R"
  P120_FREQ: "P120_FREQ"
  P130_ST: "P130_ST"
  LF04_ST: "LF04_ST"
  PT131_R: "PT131_R"
  PT132_R: "PT132_R"
  FIT130_R: "FIT130_R"
  TE130_R: "TE130_R"
  TH131_R: "TH131_R"
  P130_FREQ: "P130_FREQ"
  P140_ST: "P140_ST"
  LF05_ST: "LF05_ST"
  PT141_R: "PT141_R"
  PT142_R: "PT142_R"
  FIT140_R: "FIT140_R"
  TE140_R: "TE140_R"
  TH141_R: "TH141_R"
  P140_FREQ: "P140_FREQ"
