lagoon_id: vida_lagoon
product_type: crystal
source: rockwell
poll_seconds: 1
timezone: America/Buenos_Aires

backend:
  url: http://127.0.0.1:8090/ingest/scada
  timeout_sec: 5

rockwell:
  ip: 192.168.15.10
  timeout_sec: 5

tags:
  PT117_R_SCADA: PT117_R_SCADA
  PT120_R_SCADA: PT120_R_SCADA
  PT154_R_SCADA: PT154_R_SCADA
  PT157_R_SCADA: PT157_R_SCADA
  FIT003_R_SCADA: FIT003_R_SCADA
  WM01_TOT: WM01_TOT
  BACKWASH.DIFF_PRES: BACKWASH.DIFF_PRES
  P002_STS_SCADA: P002_STS_SCADA
  P006_STS_SCADA: P006_STS_SCADA
  P007_STS_SCADA: P007_STS_SCADA
  RETRO_SCADA: RETRO_SCADA
  P017_STS_SCADA: P017_STS_SCADA
  P016_STS_SCADA: P016_STS_SCADA
  P015_STS_SCADA: P015_STS_SCADA
  VE288_STS_SCADA: VE288_STS_SCADA
  VE318_STS_SCADA: VE318_STS_SCADA
  VE320_STS_SCADA: VE320_STS_SCADA
  VE322_STS_SCADA: VE322_STS_SCADA

event_tags:
  P002_STS_SCADA: STATE
  P006_STS_SCADA: STATE
  P007_STS_SCADA: STATE
  P017_STS_SCADA: STATE
  P016_STS_SCADA: STATE
  P015_STS_SCADA: STATE
  VE288_STS_SCADA: STATE
  VE318_STS_SCADA: STATE
  VE320_STS_SCADA: STATE
  VE322_STS_SCADA: STATE
